apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvclaim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
