#!/bin/bash
sudo yum install wget unzip httpd -y  #for non root user
sudo systemctl start httpd
sudo systemctl enable httpd 
mkdir -p /tmp/webfiles                #if directory exists it will not through error
cd /tmp/webfiles
wget https://www.tooplate.com/zip-templates/2124_vertex.zip
unzip 2124_vertex.zip
sudo cp 2124_vertex/* /var/www/html/   #/var/www/html/ directory owned by root user so use sudo
systemctl restart httpd
systemctl status httpd
rm -rf /tmp/webfiles

===================================== Script write user friendly ===============================================

Need to write comments and print messages for easy understanding and simple 

https://linuxhint.com/what_is_dev_null/

It’s a special file that’s present in every single Linux system. However, unlike most other virtual files, instead of reading,
it’s used to write. Whatever you write to /dev/null will be discarded, forgotten into the void. It’s known as the null device
in a UNIX system.


############## Script.sh ################

#!/bin/bash

#INSTALLING PACKAGES
echo "#################################"
echo "installing packages"
echo "#################################"
sudo yum install wget unzip httpd -y > /dev/null                      #for non root user #/dev/null will not show o/p on console
echo 

#START AND ENABLE SERVICE
echo "#################################"
echo "Start and enable http service"
echo "#################################"
sudo systemctl start httpd
sudo systemctl enable httpd 
echo

#CREATE /TMP DIRECTORY 7 ARTIFACT DEPLOYMENT
echo "#################################"
echo "Starting and artifact deployment"
echo "#################################"
mkdir -p /tmp/webfiles                                                  #if directory exists it will not through error
cd /tmp/webfiles

wget https://www.tooplate.com/zip-templates/2126_antique_cafe.zip > /dev/null 
unzip 2126_antique_cafe.zip > /dev/null 
sudo cp -r 2126_antique_cafe/* /var/www/html/                             #/var/www/html/ directory owned by root user so use sudo

#START HTTPD SERVICE
echo "#################################"
echo "Starting and artifact deployment"
echo "#################################"
systemctl restart httpd 
echo

#REMOVE TEMPORARY FILES
echo "#################################"
echo "Starting and artifact deployment"
echo "#################################"
rm -rf /tmp/webfiles
echo

sudo systemctl status httpd

=============================================================================

Try searching on your browser <ip>:80  webiste able to access or not


[root@ip-172-31-10-46 ~]# cd /var/www/html
[root@ip-172-31-10-46 html]# ls
ABOUT THIS TEMPLATE.txt  css  img  index.html  js  webfonts



