#!/bin/bash
read -p "Enter the number: " NUM
echo

if [ $NUM -gt 100 ]
then 
  echo "We have entered if block"
  sleep 3
  echo "You number is greaterthan 100"
  date
fi

echo "Script execution is completed successfully"
========================================================

Execute:
--------

[root@ip-172-31-10-46 ~]# sh s1.sh
Enter the number: 103

We have entered if block
You number is greaterthan 100
Wed Jul 20 15:16:59 UTC 2022
Script execution is completed successfully


Enter number less than 100 and check it will not enter if block simply 

[root@ip-172-31-10-46 ~]# sh s1.sh
Enter the number: 23

Script execution is completed successfully
